spring.application.name=SpringMinio

spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB


minio.bucket.name=springminio
#minio.default.folder=/
#server.port=8000  
minio.access.key=PFg7QuQn5GSLeDu1QxE8
minio.secret.key=0DmAjCOkfS4FMXXGEgQeb0gzRFrIrX0L7QxxaCEP

minio.url=http://127.0.0.1:9000
