apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-demo-app
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/abduldanish/knativedemoapp:5.0
      # timeoutSeconds: 600
