apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    app: voting-app
    type: backend
spec:
  type: NodePort
  ports:
    - targetPort: 8020
      port: 8020
      nodePort: 30020
  selector:
    app: voting-app
    type: backend